{% set version = "0.11.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-networkdynamic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/networkDynamic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/networkDynamic/networkDynamic_{{ version }}.tar.gz
  sha256: 2c664fd0d85c0cdc099480d67a18e6afbb0cc1036963b6664a8a756874648e5b

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-network >=1.17.0
    - r-networklite
    - r-statnet.common
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-network >=1.17.0
    - r-networklite
    - r-statnet.common

test:
  commands:
    - $R -e "library('networkDynamic')"           # [not win]
    - "\"%R%\" -e \"library('networkDynamic')\""  # [win]

about:
  home: http://statnet.org
  license: GPL-3.0-only
  summary: Simple interface routines to facilitate the handling of network objects with complex intertemporal data. This is a part of the "statnet" suite of packages for network analysis.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: networkDynamic
# Version: 0.10.0
# Date: 2019-04-04
# Title: Dynamic Extensions for Network Objects
# Type: Package
# Depends: R (>= 3.0.0), network (>= 1.15)
# Imports: statnet.common, methods
# Suggests: testthat
# LinkingTo: network
# Authors@R: c( person("Carter T.", "Butts", role=c("aut"), email="buttsc@uci.edu"), person("Ayn", "Leslie-Cook", role=c("aut"), email="aynlc3@uw.edu"), person("Pavel N.", "Krivitsky", role=c("aut"), email="pavel@uow.edu.au"), person("Skye", "Bender-deMoll", role=c("aut","cre"), email="skyebend@uw.edu"), person("Zack", "Almquist", role=c("ctb"), email="almquist@uci.edu"), person("David R.", "Hunter", role=c("ctb"), email="dhunter@stat.psu.edu"), person("Li","Wang",role=c("ctb"),email="lxwang@gmail.com"), person("Kirk","Li",role=c("ctb"),email="kirkli@uw.edu"), person("Steven M.","Goodreau",role=c("ctb"),email="goodreau@uw.edu"), person("Jeffrey", "Horner", role=c("ctb"), email="jeffrey.horner@gmail.com"), person("Martina", "Morris", role=c("ctb"), email="morrism@u.washington.edu"))
# Description: Simple interface routines to facilitate the handling of network objects with complex intertemporal data. This is a part of the "statnet" suite of packages for network analysis.
# License: GPL-3
# LazyLoad: yes
# URL: http://statnet.org
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-04-05 07:12:42 UTC; skyebend
# Author: Carter T. Butts [aut], Ayn Leslie-Cook [aut], Pavel N. Krivitsky [aut], Skye Bender-deMoll [aut, cre], Zack Almquist [ctb], David R. Hunter [ctb], Li Wang [ctb], Kirk Li [ctb], Steven M. Goodreau [ctb], Jeffrey Horner [ctb], Martina Morris [ctb]
# Maintainer: Skye Bender-deMoll <skyebend@uw.edu>
# Repository: CRAN
# Date/Publication: 2019-04-05 09:50:05 UTC
