# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ctarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dTSChfYT6uVLSAqTwfp0TlkqaOn3EVeqr1gBZUQQhtLVqwaGlEvu4d3gME1gMjxFkmIVIoYUo1ry079PNCS8KCkvZPt+wx0UCHoOPv9vhInmr+9teuhpe6eytDGk3PmDtMS1OKvmk3vyKk5HSlGJlZWgBbdcXRr7aaa32OAS3wJmRZi2Ee5SEwD6lPGC9yTSP9GeHnO/iKGWP8NCBscgZrc34SklWnGvsAp1IMGeuI2LqK6SBmArFX4MGqvmnp6Jv7RCcazAsmJJSngox9pujaq27ezYe8c3BiTXZ+WJiI5iImtBIK7RdkE9EivRcqIYrJQmO0vx97KvBKZ338JZC/0QZpIAPUC3M6gl9oH9Sg+5pbt8DCnztIh7x9gktBl3CKEYAs0E8zXr7TRV5HIxiHoTFfnzh/Ga1wnLMtwrRt0fBFCXSf1Ig/lp/UwDgWhJhrGIcD2sF9pFmDlZEMgZIhNQCMRvadVWBFE8HTShhcLfowOjjmHgC2mdKbcvSGCogP9bMpKq0eUnwbqmlvdmYyLjGJlj8K81hc+FNtM4Bdv7ni3WVvZ2hx6c1rt+cS/0DdL8xVn+mINboIdgLEDmBvBSvPphKYx0w+b50OSZjKUPThe7Xg3mfZzMUxHziT/LMCiqiFKmjlRW3c2VSu7E23Y1C2HQBDXORAmJXM5RYyc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
