appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: dTSChfYT6uVLSAqTwfp0TlkqaOn3EVeqr1gBZUQQhtLVqwaGlEvu4d3gME1gMjxFkmIVIoYUo1ry079PNCS8KCkvZPt+wx0UCHoOPv9vhInmr+9teuhpe6eytDGk3PmDtMS1OKvmk3vyKk5HSlGJlZWgBbdcXRr7aaa32OAS3wJmRZi2Ee5SEwD6lPGC9yTSP9GeHnO/iKGWP8NCBscgZrc34SklWnGvsAp1IMGeuI2LqK6SBmArFX4MGqvmnp6Jv7RCcazAsmJJSngox9pujaq27ezYe8c3BiTXZ+WJiI5iImtBIK7RdkE9EivRcqIYrJQmO0vx97KvBKZ338JZC/0QZpIAPUC3M6gl9oH9Sg+5pbt8DCnztIh7x9gktBl3CKEYAs0E8zXr7TRV5HIxiHoTFfnzh/Ga1wnLMtwrRt0fBFCXSf1Ig/lp/UwDgWhJhrGIcD2sF9pFmDlZEMgZIhNQCMRvadVWBFE8HTShhcLfowOjjmHgC2mdKbcvSGCogP9bMpKq0eUnwbqmlvdmYyLjGJlj8K81hc+FNtM4Bdv7ni3WVvZ2hx6c1rt+cS/0DdL8xVn+mINboIdgLEDmBvBSvPphKYx0w+b50OSZjKUPThe7Xg3mfZzMUxHziT/LMCiqiFKmjlRW3c2VSu7E23Y1C2HQBDXORAmJXM5RYyc=
conda_forge_output_validation: true
